theme: jekyll-theme-minimal
name: Dear Neighbors | Code for Denver
title: null
description: from Code for Denver
logo: https://raw.githubusercontent.com/codefordenver/dearneighbors/master/Dear%20Neighbors%20Logo.png
